#:schema node_modules/wrangler/config-schema.json
name = "dafei843"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f98252d5579f41f9bf4d55c6d2b6012b" }
]

[assets]
directory = "./public"
